name = "Buku Masjid"
license = "MIT"
licenselink = "https://github.com/buku-masjid/docs/blob/master/LICENSE"
description = "Panduan pengguanan sistem Buku Masjid."

homepage = "https://github.com/buku-masjid/docs"
demosite = "https://bukumasjid.com"

tags = []
features = []

[author]
  name = "Nafies Luthfi"
  homepage = "https://blog.nafies.id"
